// <auto-generated />
namespace VeterenaryClinic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Communication_Add_AdditionalPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Communication_Add_AdditionalPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "202011101038529_Communication_Add_AdditionalPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
